name: Import Configurations
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: v1.0.6
      FULL_FILE_NAME: iamctl-1.0.6-linux-x64.tar.gz
      FILE_NAME: iamctl-1.0.6
      ENV_NAME: ${{ env.ENV_NAME }}
    steps:
      - name: Download files from the current repository
        uses: actions/checkout@v2
    
      - name: Download and unzip latest identity-tools-cli release
        run: |
          # Download the release file
          curl -L -o "${FULL_FILE_NAME}" "https://github.com/wso2-extensions/identity-tools-cli/releases/download/${RELEASE_VERSION}/${FULL_FILE_NAME}"
          tar -xzf "${FULL_FILE_NAME}"
          
      - name: Extract release file
        run: tar -xzf "${FULL_FILE_NAME}"
      
      - name: Run import command
        run: |
          cd "${FILE_NAME}/bin"
          ./iamctl importAll -c "../../configs/$ENV_NAME" -i "../../"
